# Generated by Django 5.2 on 2025-04-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_trip_results_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at']},
        ),
    ]
