# Generated by Django 5.2 on 2025-04-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_trip_options'),
        ('core', '0004_userpreference'),
    ]

    operations = [
    ]
